version: '3.1'

services:
  rentaCar:
    container_name: c_api_rentacar
    image: enes/rentacar
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
        - 80:80 
    networks:
      - micro_net

networks:
  micro_net:
   driver: 'bridge'